### ISSUE TITLE
Issue with visual layout of the dialog

### ISSUE THREAD

**Issue by CyrilleB79** [marlon-sousa/EnhancedFindDialog#14]
Hello Marlon

### Issue

The find dialog of this add-on has a very bad layout. It is missing margins around and between controls. It is specifically very bad for visually impaired people who may have difficulty to identify and separate two adjacent controls or even the content of the find window and the content of the window below.

### Solution
Copy the way NVDA's find dialog is made to get a similar layout.

Many thanks.

**Comment by thgcode** [comment]
Hello!
@CyrilleB79 I tried to copy as much as I could from NVDA's find dialog on pull request #16 . Can you validate if it looks correctly?
Thanks!

**Comment by thgcode** [comment]
I updated both pull requests so they will compile on GitHub and include a .nvda-addon for anyone wanting to test the changes without compiling.

**Comment by CyrilleB79** [comment]
Fixed in 1.4.1. Thanks @thgcode !
