### ISSUE TITLE
Include NVDA's find dialog improvements

### ISSUE THREAD

**Issue by CyrilleB79** [marlon-sousa/EnhancedFindDialog#19]
This add-on is based on NVDA's find dialog and code has been copied and modified from there.

Since then, NVDA has received minor improvements regarding the search function:
* [#11564](https://github.com/nvaccess/nvda/pull/11564)
* [#11771](https://github.com/nvaccess/nvda/pull/11771) 

[#11564](https://github.com/nvaccess/nvda/pull/11564) is currently being integrated in the add-on thanks to #17.

[#11771](https://github.com/nvaccess/nvda/pull/11771) still needs to be integrated in this add-on. Thanks.

**Comment by thgcode** [comment]
Thanks! I created a new pull request to fix the reverse feature. During testing I also found that reverse was searching forward if the text field was empty and search wrap was enabled, also tried to fix this issue.

**Comment by CyrilleB79** [comment]
Fixed in version 1.4.1. Thanks @thgcode !
