### ISSUE TITLE
The addon removes find features from the input gestures.

### ISSUE THREAD

**Issue by chigkim** [marlon-sousa/EnhancedFindDialog#32]
First, great addon!
I wanted to remap shortcuts for find features for browse mode to different shortcuts.
I typed the word "find" in the filtered by in the input gestures dialog, and the result was empty.
I removed the enhanced find dialog and searched again, and they appeared inside the browse mode.
Just out of curiosity, I reinstalled the addon, and searched again, and the result was empty.
I'm on nvda 2024.2.rc2.
Could you look into it?
Thanks so much!

**Comment by thgcode** [comment]
Hello!
I also can reproduce it with NVDA 2024.2, tonight I will look on the code of NVDA 2024.2 to see if we missed something that was added to try to fix it.
