### ISSUE TITLE
EnhancedFindDialog: NVDA 2022.1 compatibility

### ISSUE THREAD

**Issue by surfer0627** [marlon-sousa/EnhancedFindDialog#6]
Note: this is a Add-on API compatibility breaking release. Add-ons will need to be re-tested and have their manifest updated. 

* [NVDA 2022.1beta4 available for testing](https://www.nvaccess.org/post/nvda-2022-1beta4/)

cc: @marlon-sousa 

Thank you for your help.

**Comment by marlon-sousa** [comment]
Hello,

My addons will be updated short after the official version is released.

I will let you know through this issue and also via e-mail.

**Comment by surfer0627** [comment]
Hi @marlon-sousa,
Thank you for your add-on and contributions.

**Comment by marlon-sousa** [comment]
Closed by #7
